"""Decision bridge for the test-generator agent.

Converts a generated-test artifact (target module + test content +
base SHA) into three chained Decisions that the framework can route
through WriteMode + dedupe:

1. ``create_branch``  — branch off ``base_sha`` on ``base_branch``
2. ``update_file``    — write the generated test onto that branch
3. ``open_pr``        — open a PR from the new branch into ``base_branch``

The three Decisions share a branch name (deterministic, so retries
dedupe cleanly) and confidence. Each carries its own action-specific
evidence strings so the COMMENT-mode downgrade path renders a
self-describing comment — reviewers can see what GITA *wanted* to
do without executing anything.

The caller is responsible for executing the three Decisions in list
order and stopping on failure; no in-bridge orchestration.
"""
from __future__ import annotations

import hashlib
import logging
import re
from dataclasses import dataclass
from typing import Any

from gita.agents.decisions import Decision

logger = logging.getLogger(__name__)

_BRANCH_SLUG_RE = re.compile(r"[^A-Za-z0-9]+")
_SHA_PREFIX_LEN = 7


@dataclass(frozen=True)
class TestGenerationArtifact:
    """Inputs the bridge needs to materialize the three Decisions.

    Keep this immutable — the bridge is pure and idempotent; callers
    build an artifact, pass it in, and get the same three Decisions
    back every time.
    """

    # Tell pytest not to collect this — the ``Test*`` prefix names the
    # domain concept ("test generation artifact"), not a pytest class.
    __test__ = False

    repo: str                           # "owner/repo"
    base_branch: str                    # "main"
    base_sha: str                       # commit SHA to branch from
    target_file: str                    # module being tested, repo-relative
    test_file_path: str                 # where to write the test file
    test_content: str                   # the generated pytest code
    existing_test_sha: str | None = None  # blob SHA if the test file exists
    pr_title: str | None = None         # None → default
    pr_body: str | None = None          # None → default
    fallback_issue: int | None = None   # landing spot for COMMENT downgrade
    confidence: float = 0.9


# ---------------------------------------------------------------------------
# Naming helpers (also re-used by the recipe + CLI surfaces)
# ---------------------------------------------------------------------------
def compute_branch_name(target_file: str, base_sha: str) -> str:
    """Deterministic branch name from (target_file, base_sha).

    Strips the ``.py`` extension, collapses non-alphanumeric runs to
    single hyphens, appends the first 7 chars of the base SHA so a
    retry at the same tree reuses the same branch (and therefore the
    same dedupe signature).
    """
    stem = target_file[:-3] if target_file.endswith(".py") else target_file
    slug = _BRANCH_SLUG_RE.sub("-", stem).strip("-").lower()
    sha_prefix = (base_sha or "unknown")[:_SHA_PREFIX_LEN] or "unknown"
    return f"gita/tests/{slug}-{sha_prefix}"


def default_pr_title(target_file: str) -> str:
    name = target_file.rsplit("/", 1)[-1]
    return f"tests: add coverage for {name}"


def default_pr_body(
    target_file: str, test_file_path: str, content_hash_prefix: str
) -> str:
    return (
        f"Auto-generated tests for `{target_file}`.\n"
        f"\n"
        f"- New file: `{test_file_path}`\n"
        f"- Content hash: `{content_hash_prefix}…`\n"
        f"- Generated by GITA (test-generator agent).\n"
        f"\n"
        f"Review the generated assertions carefully — AI-produced "
        f"tests can be syntactically valid but behaviourally wrong."
    )


# ---------------------------------------------------------------------------
# The bridge itself
# ---------------------------------------------------------------------------
def build_test_generation_decisions(
    artifact: TestGenerationArtifact,
) -> list[Decision]:
    """Return ``[create_branch, update_file, open_pr]`` for the artifact.

    All three share ``confidence`` and (when set) ``fallback_issue``,
    so a COMMENT-mode run downgrades each in place to a comment on
    the fallback issue. Execute in list order; stop on the first
    non-executed outcome.
    """
    branch_name = compute_branch_name(
        artifact.target_file, artifact.base_sha
    )
    ref_name = f"refs/heads/{branch_name}"

    content_hash = hashlib.sha256(
        artifact.test_content.encode("utf-8")
    ).hexdigest()
    content_hash_prefix = content_hash[:12]

    pr_title = artifact.pr_title or default_pr_title(artifact.target_file)
    pr_body = artifact.pr_body or default_pr_body(
        artifact.target_file,
        artifact.test_file_path,
        content_hash_prefix,
    )

    target_base: dict[str, Any] = {"repo": artifact.repo}
    if artifact.fallback_issue is not None:
        target_base["fallback_issue"] = int(artifact.fallback_issue)

    # ---- 1. create_branch -------------------------------------------------
    create_branch = Decision(
        action="create_branch",
        target=dict(target_base),
        payload={"ref": ref_name, "base_sha": artifact.base_sha},
        evidence=[
            (
                f"would create branch `{branch_name}` from base SHA "
                f"`{artifact.base_sha[:_SHA_PREFIX_LEN]}` on "
                f"`{artifact.base_branch}`"
            ),
            f"purpose: add tests for `{artifact.target_file}`",
        ],
        confidence=artifact.confidence,
    )

    # ---- 2. update_file ---------------------------------------------------
    mode_label = (
        "update existing" if artifact.existing_test_sha else "create new"
    )
    file_payload: dict[str, Any] = {
        "path": artifact.test_file_path,
        "content": artifact.test_content,
        "message": (
            f"gita: add generated tests for {artifact.target_file}"
        ),
        "branch": branch_name,
    }
    if artifact.existing_test_sha:
        file_payload["sha"] = artifact.existing_test_sha

    update_file = Decision(
        action="update_file",
        target=dict(target_base),
        payload=file_payload,
        evidence=[
            (
                f"would write `{artifact.test_file_path}` "
                f"({len(artifact.test_content)} bytes, "
                f"sha256 `{content_hash_prefix}…`) "
                f"onto `{branch_name}`"
            ),
            f"mode: {mode_label}",
            # Full proposed content is rendered by
            # ``_render_downgrade_body`` from ``payload.content`` so the
            # code fence survives outside the evidence bullet list.
        ],
        confidence=artifact.confidence,
    )

    # ---- 3. open_pr -------------------------------------------------------
    open_pr = Decision(
        action="open_pr",
        target=dict(target_base),
        payload={
            "title": pr_title,
            "body": pr_body,
            "head": branch_name,
            "base": artifact.base_branch,
        },
        evidence=[
            (
                f"would open PR `{pr_title}` from `{branch_name}` "
                f"into `{artifact.base_branch}`"
            ),
            f"purpose: ship generated tests for `{artifact.target_file}`",
        ],
        confidence=artifact.confidence,
    )

    return [create_branch, update_file, open_pr]
