"""Tests for src.tools.github.comments — post/edit with Redis dedup."""

import pytest
from unittest.mock import AsyncMock, patch, MagicMock

from src.tools.github.comments import _post_comment, _edit_comment, make_post_comment, make_edit_comment


@pytest.fixture
def mock_client():
    client = AsyncMock()
    client.get = AsyncMock(return_value=[])
    client.post = AsyncMock(return_value={"id": 999, "body": "test", "html_url": "https://github.com/..."})
    client.patch = AsyncMock(return_value={"id": 999, "body": "edited", "html_url": "https://github.com/..."})
    return client


class TestPostComment:
    @patch("src.tools.github.comments.GitHubClient")
    @patch("src.tools.github.comments._get_redis")
    async def test_success_posts_comment(self, mock_redis_fn, mock_client_cls, mock_client):
        mock_redis = AsyncMock()
        mock_redis.set = AsyncMock(return_value=True)  # Lock acquired
        mock_redis.delete = AsyncMock()
        mock_redis_fn.return_value = mock_redis
        mock_client_cls.return_value = mock_client
        mock_client.get = AsyncMock(return_value=[])  # No existing bot comments

        result = await _post_comment(1001, "owner/repo", 5, "Test comment")

        assert result.success is True
        mock_client.post.assert_called_once()

    @patch("src.tools.github.comments.GitHubClient")
    @patch("src.tools.github.comments._get_redis")
    async def test_lock_not_acquired_skips(self, mock_redis_fn, mock_client_cls, mock_client):
        mock_redis = AsyncMock()
        mock_redis.set = AsyncMock(return_value=None)  # Lock NOT acquired
        mock_redis_fn.return_value = mock_redis
        mock_client_cls.return_value = mock_client

        result = await _post_comment(1001, "owner/repo", 5, "Test comment")

        assert result.success is True
        assert result.data.get("skipped") is True
        mock_client.post.assert_not_called()

    @patch("src.tools.github.comments.GitHubClient")
    @patch("src.tools.github.comments._get_redis")
    async def test_existing_bot_comment_skips(self, mock_redis_fn, mock_client_cls, mock_client):
        mock_redis = AsyncMock()
        mock_redis.set = AsyncMock(return_value=True)
        mock_redis.delete = AsyncMock()
        mock_redis_fn.return_value = mock_redis
        mock_client_cls.return_value = mock_client
        # Existing comment with bot signature
        mock_client.get = AsyncMock(return_value=[
            {"id": 100, "body": "Previous analysis\n---\n*Generated by GitHub Assistant — Issue Analyst*",
             "user": {"type": "Bot"}}
        ])

        result = await _post_comment(1001, "owner/repo", 5, "New comment")

        assert result.success is True
        assert result.data.get("skipped") is True

    @patch("src.tools.github.comments.GitHubClient")
    @patch("src.tools.github.comments._get_redis")
    async def test_post_failure_releases_lock(self, mock_redis_fn, mock_client_cls, mock_client):
        mock_redis = AsyncMock()
        mock_redis.set = AsyncMock(return_value=True)
        mock_redis.delete = AsyncMock()
        mock_redis_fn.return_value = mock_redis
        mock_client_cls.return_value = mock_client
        mock_client.get = AsyncMock(return_value=[])
        mock_client.post = AsyncMock(side_effect=Exception("API error"))

        result = await _post_comment(1001, "owner/repo", 5, "Test")

        assert result.success is False
        mock_redis.delete.assert_called_once()


class TestEditComment:
    @patch("src.tools.github.comments.GitHubClient")
    async def test_success(self, mock_client_cls, mock_client):
        mock_client_cls.return_value = mock_client

        result = await _edit_comment(1001, "owner/repo", 999, "Updated body")

        assert result.success is True
        mock_client.patch.assert_called_once()

    @patch("src.tools.github.comments.GitHubClient")
    async def test_failure(self, mock_client_cls):
        client = AsyncMock()
        client.patch = AsyncMock(side_effect=Exception("Not found"))
        mock_client_cls.return_value = client

        result = await _edit_comment(1001, "owner/repo", 999, "Body")

        assert result.success is False
        assert "Not found" in result.error


class TestFactories:
    def test_make_post_comment(self):
        tool = make_post_comment(1001, "owner/repo")
        assert tool.name == "post_comment"
        assert "issue_number" in tool.parameters.get("properties", {})

    def test_make_edit_comment(self):
        tool = make_edit_comment(1001, "owner/repo")
        assert tool.name == "edit_comment"
        assert "comment_id" in tool.parameters.get("properties", {})
