"""Decision bridges — turn an OnboardingResult into Decision objects.

Two bridges:

1. ``build_onboarding_comment_decision`` — wraps the entire result as one
   ``comment`` Decision. Used by the Week 2 ``--post-to`` flow.
2. ``build_onboarding_issue_decisions`` — wraps each milestone as a
   separate ``create_issue`` Decision. Used by the Week 3
   ``--create-issues`` flow.

Both are pure functions: they take an ``OnboardingResult`` and return
``Decision`` objects without any I/O.
"""
from __future__ import annotations

import logging
from typing import Any

from gita.agents.decisions import Decision
from gita.agents.types import Finding, Milestone, OnboardingResult

logger = logging.getLogger(__name__)

# Findings or milestones counts at or above this threshold get collapsed
# into <details> blocks so the comment body stays scannable on GitHub.
_COLLAPSE_THRESHOLD = 4


# ---------------------------------------------------------------------------
# Shared rendering helpers
# ---------------------------------------------------------------------------
def _wrap_details(
    summary: str, body_lines: list[str], *, collapse: bool
) -> list[str]:
    """Optionally wrap a block in a collapsible ``<details>`` section."""
    if not collapse:
        return body_lines
    wrapped = ["<details>", f"<summary>{summary}</summary>", ""]
    wrapped.extend(body_lines)
    wrapped.append("</details>")
    return wrapped


def _render_finding_block(index: int, finding: Finding) -> list[str]:
    block = [
        f"**{index + 1}. [{finding.severity.upper()}] {finding.kind}** "
        f"— `{finding.file}:{finding.line}`",
        "",
        finding.description,
    ]
    if finding.fix_sketch:
        block.append("")
        block.append(f"_Fix sketch:_ {finding.fix_sketch}")
    block.append("")
    return block


def _render_milestone_block(milestone: Milestone) -> list[str]:
    block = [
        f"**{milestone.title}** _(confidence {milestone.confidence:.2f})_",
        "",
        milestone.summary,
    ]
    if milestone.finding_indices:
        citations = ", ".join(
            f"finding {i + 1}" for i in milestone.finding_indices
        )
        block.append("")
        block.append(f"_Addresses:_ {citations}")
    block.append("")
    return block


# ---------------------------------------------------------------------------
# Comment bridge (Week 2 Day 7)
# ---------------------------------------------------------------------------
def _render_comment_body(result: OnboardingResult) -> str:
    """Render the OnboardingResult as a markdown comment body."""
    lines: list[str] = [
        f"## GITA onboarding review for `{result.repo_name}`",
        "",
        result.project_summary,
        "",
    ]

    if result.findings:
        heading = f"### Findings ({len(result.findings)})"
        collapse = len(result.findings) >= _COLLAPSE_THRESHOLD
        findings_block: list[str] = []
        for i, finding in enumerate(result.findings):
            findings_block.extend(_render_finding_block(i, finding))
        if collapse:
            lines.extend(
                _wrap_details(
                    f"Findings ({len(result.findings)}) — click to expand",
                    findings_block,
                    collapse=True,
                )
            )
            lines.append("")
        else:
            lines.append(heading)
            lines.append("")
            lines.extend(findings_block)
    else:
        lines.append("_No concrete findings — the reviewed files looked clean._")
        lines.append("")

    if result.milestones:
        heading = f"### Proposed milestones ({len(result.milestones)})"
        collapse = len(result.milestones) >= _COLLAPSE_THRESHOLD
        milestones_block: list[str] = []
        for milestone in result.milestones:
            milestones_block.extend(_render_milestone_block(milestone))
        if collapse:
            lines.extend(
                _wrap_details(
                    f"Proposed milestones ({len(result.milestones)}) — "
                    f"click to expand",
                    milestones_block,
                    collapse=True,
                )
            )
            lines.append("")
        else:
            lines.append(heading)
            lines.append("")
            lines.extend(milestones_block)

    lines.append("---")
    lines.append(
        f"_Generated by GITA v0.1.0 against the local index. "
        f"Overall confidence: {result.confidence:.2f}._"
    )
    return "\n".join(lines)


def build_onboarding_comment_decision(
    result: OnboardingResult,
    repo_full_name: str,
    issue_number: int,
) -> Decision:
    """Wrap an OnboardingResult as a ``comment`` Decision."""
    evidence = [
        f"{len(result.findings)} concrete findings produced",
        f"{len(result.milestones)} proposed milestones",
        f"agent overall confidence: {result.confidence:.2f}",
    ]
    if result.findings:
        evidence.append(
            f"strongest finding: {result.findings[0].severity} "
            f"{result.findings[0].kind} at "
            f"{result.findings[0].file}:{result.findings[0].line}"
        )

    return Decision(
        action="comment",
        target={"repo": repo_full_name, "issue": issue_number},
        payload={"body": _render_comment_body(result)},
        evidence=evidence,
        confidence=result.confidence,
    )


# ---------------------------------------------------------------------------
# Issue bridge (Week 3 Day 4)
# ---------------------------------------------------------------------------
def _render_issue_body(
    milestone: Milestone,
    findings: list[Finding],
    source_repo: str,
) -> str:
    """Render an issue body for a single milestone."""
    lines: list[str] = [milestone.summary.strip(), ""]

    cited = [
        findings[i]
        for i in milestone.finding_indices
        if 0 <= i < len(findings)
    ]
    if cited:
        checklist: list[str] = []
        for finding in cited:
            checklist.append(
                f"- [ ] **[{finding.severity.upper()}] {finding.kind}** "
                f"at `{finding.file}:{finding.line}` — {finding.description}"
            )
            if finding.fix_sketch:
                checklist.append(
                    f"      _Fix sketch:_ {finding.fix_sketch}"
                )

        if len(cited) >= _COLLAPSE_THRESHOLD:
            lines.extend(
                _wrap_details(
                    f"Findings ({len(cited)}) — click to expand",
                    checklist,
                    collapse=True,
                )
            )
        else:
            lines.append(f"## Findings ({len(cited)})")
            lines.append("")
            lines.extend(checklist)
        lines.append("")

    lines.append("---")
    lines.append(
        f"_Generated by GITA v0.1.0 onboarding agent against `{source_repo}`. "
        f"Milestone confidence: {milestone.confidence:.2f}._"
    )
    return "\n".join(lines)


def build_onboarding_issue_decisions(
    result: OnboardingResult,
    target_repo: str,
    *,
    fallback_comment_target: int | None = None,
    default_labels: list[str] | None = None,
) -> list[Decision]:
    """Wrap an OnboardingResult as a list of ``create_issue`` Decisions."""
    if not result.milestones:
        return []

    decisions: list[Decision] = []
    for milestone in result.milestones:
        cited_indices = [
            i for i in milestone.finding_indices if 0 <= i < len(result.findings)
        ]
        if not cited_indices:
            logger.warning(
                "skipping_milestone_no_valid_findings title=%s",
                milestone.title,
            )
            continue

        evidence = [
            f"milestone: {milestone.title}",
            f"agent overall confidence: {result.confidence:.2f}",
            f"source repo: {result.repo_name}",
        ]
        for idx in cited_indices:
            finding = result.findings[idx]
            evidence.append(
                f"{finding.severity} {finding.kind} at "
                f"{finding.file}:{finding.line}"
            )

        target: dict[str, Any] = {"repo": target_repo}
        if fallback_comment_target is not None:
            target["fallback_issue"] = fallback_comment_target

        sig_keys = sorted(
            f"{result.findings[i].file}:{result.findings[i].line}"
            for i in cited_indices
        )

        payload: dict[str, Any] = {
            "title": milestone.title,
            "body": _render_issue_body(
                milestone, result.findings, result.repo_name
            ),
            "_signature_keys": sig_keys,
        }
        if default_labels:
            payload["labels"] = list(default_labels)

        decisions.append(
            Decision(
                action="create_issue",
                target=target,
                payload=payload,
                evidence=evidence,
                confidence=milestone.confidence,
            )
        )

    return decisions
