"""add onboarding_runs and file_mappings

Revision ID: 1ec4ee5b6a75
Revises: cc95384e29e1
Create Date: 2026-04-02 20:57:34.193338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ec4ee5b6a75'
down_revision: Union[str, None] = 'cc95384e29e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('repo_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('existing_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actions_taken', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('milestones_created', sa.Integer(), nullable=False),
    sa.Column('milestones_updated', sa.Integer(), nullable=False),
    sa.Column('issues_created', sa.Integer(), nullable=False),
    sa.Column('issues_updated', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'file_path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_mappings')
    op.drop_table('onboarding_runs')
    # ### end Alembic commands ###
