"""
GitHub tools for comment operations.

Three layers of duplicate prevention:
1. Bot self-detection at webhook level (webhooks.py)
2. Redis lock per issue — only one comment per issue within a time window
3. Existing bot comment check — scans issue comments for our signature
"""

import redis.asyncio as aioredis
from src.core.github_auth import GitHubClient
from src.core.config import settings
from src.tools.base import Tool, ToolResult
from src.tools.db.entity_sync import persist_comment, persist_comments_batch

# Bot signature that appears in all our comments
BOT_SIGNATURE = "Generated by GitHub Assistant"

# Redis client — initialized on first use
_redis = None


async def _get_redis():
    global _redis
    if _redis is None:
        _redis = aioredis.from_url(settings.redis_url)
    return _redis


async def _post_comment(installation_id: int, repo_full_name: str, issue_number: int, body: str, repo_id: int = 0) -> ToolResult:
    """
    Post a comment with triple dedup protection:
    1. Redis lock — atomic, prevents race conditions between parallel agents
    2. Existing comment check — prevents duplicates across separate events
    """
    # LAYER 3a: Redis lock — atomic set-if-not-exists with TTL
    r = await _get_redis()
    lock_key = f"comment_lock:{repo_full_name}:{issue_number}"
    acquired = await r.set(lock_key, "1", ex=120, nx=True)  # 2 min TTL

    if not acquired:
        return ToolResult(
            success=True,
            data={"skipped": True, "reason": "Another agent is already commenting on this issue"},
        )

    # LAYER 3b: Check for existing bot comment
    client = GitHubClient(installation_id)
    try:
        comments = await client.get(
            f"/repos/{repo_full_name}/issues/{issue_number}/comments",
            params={"per_page": 100},
        )

        # Side-effect: persist fetched comments for RAG
        if repo_id and comments:
            try:
                await persist_comments_batch(repo_id, comments, "issue", issue_number)
            except Exception:
                pass

        for comment in comments:
            if BOT_SIGNATURE in comment.get("body", ""):
                return ToolResult(
                    success=True,
                    data={"skipped": True, "reason": "Bot already commented on this issue"},
                )
    except Exception:
        pass  # If we can't check, proceed cautiously

    # Post the comment
    try:
        data = await client.post(
            f"/repos/{repo_full_name}/issues/{issue_number}/comments",
            json={"body": body},
        )

        # Side-effect: persist the new comment we just posted
        if repo_id and data.get("id"):
            try:
                await persist_comment(repo_id, data, "issue", issue_number)
            except Exception:
                pass

        return ToolResult(success=True, data={"id": data["id"], "html_url": data["html_url"]})
    except Exception as e:
        # Release lock on failure so another agent can try
        await r.delete(lock_key)
        return ToolResult(success=False, error=str(e))


async def _edit_comment(installation_id: int, repo_full_name: str, comment_id: int, body: str) -> ToolResult:
    client = GitHubClient(installation_id)
    try:
        data = await client.patch(
            f"/repos/{repo_full_name}/issues/comments/{comment_id}",
            json={"body": body},
        )
        return ToolResult(success=True, data={"id": data["id"], "html_url": data["html_url"]})
    except Exception as e:
        return ToolResult(success=False, error=str(e))


async def _upsert_tracked_comment(
    installation_id: int,
    repo_full_name: str,
    issue_number: int,
    body: str,
    marker: str,
    repo_id: int = 0,
) -> ToolResult:
    """
    Post-or-edit a tracked comment identified by a hidden HTML marker.

    First time: posts a new comment with <!-- marker --> embedded.
    Subsequent times: finds the existing comment by marker and edits it in place.

    This is how the progress tracker keeps ONE living comment per Milestone Tracker
    instead of spamming new comments on every update.
    """
    marker_tag = f"<!-- {marker} -->"
    client = GitHubClient(installation_id)

    # Search for existing comment with this marker
    existing_comment_id = None
    try:
        comments = await client.get(
            f"/repos/{repo_full_name}/issues/{issue_number}/comments",
            params={"per_page": 100},
        )

        # Side-effect: persist for RAG
        if repo_id and comments:
            try:
                await persist_comments_batch(repo_id, comments, "issue", issue_number)
            except Exception:
                pass

        for comment in comments:
            if marker_tag in comment.get("body", ""):
                existing_comment_id = comment["id"]
                break
    except Exception:
        pass

    # Embed the marker in the body (hidden in rendered markdown)
    full_body = f"{marker_tag}\n{body}"

    if existing_comment_id:
        # Edit existing
        try:
            data = await client.patch(
                f"/repos/{repo_full_name}/issues/comments/{existing_comment_id}",
                json={"body": full_body},
            )
            return ToolResult(success=True, data={
                "id": data["id"],
                "html_url": data["html_url"],
                "action": "edited",
            })
        except Exception as e:
            return ToolResult(success=False, error=f"Edit failed: {e}")
    else:
        # Post new
        try:
            data = await client.post(
                f"/repos/{repo_full_name}/issues/{issue_number}/comments",
                json={"body": full_body},
            )

            # Side-effect: persist
            if repo_id and data.get("id"):
                try:
                    await persist_comment(repo_id, data, "issue", issue_number)
                except Exception:
                    pass

            return ToolResult(success=True, data={
                "id": data["id"],
                "html_url": data["html_url"],
                "action": "created",
            })
        except Exception as e:
            return ToolResult(success=False, error=f"Post failed: {e}")


def make_upsert_tracked_comment(installation_id: int, repo_full_name: str, repo_id: int = 0) -> Tool:
    return Tool(
        name="upsert_progress_comment",
        description=(
            "Post or update a progress tracking comment on a Milestone Tracker issue. "
            "If a progress comment already exists on this issue, it will be EDITED in place "
            "(no spam). If none exists, a new one is created. Use this instead of post_comment "
            "for all milestone progress updates."
        ),
        parameters={
            "type": "object",
            "properties": {
                "issue_number": {"type": "integer", "description": "The Milestone Tracker issue number"},
                "body": {"type": "string", "description": "The full progress report (markdown). Will replace the previous version."},
            },
            "required": ["issue_number", "body"],
        },
        handler=lambda issue_number, body: _upsert_tracked_comment(
            installation_id, repo_full_name, issue_number, body,
            marker=f"gita:progress:{issue_number}",
            repo_id=repo_id,
        ),
    )


def make_post_comment(installation_id: int, repo_full_name: str, repo_id: int = 0) -> Tool:
    return Tool(
        name="post_comment",
        description="Post a comment on an issue or PR. Automatically prevents duplicates — only one bot comment per issue.",
        parameters={
            "type": "object",
            "properties": {
                "issue_number": {"type": "integer", "description": "Issue or PR number"},
                "body": {"type": "string", "description": "Comment body (markdown)"},
            },
            "required": ["issue_number", "body"],
        },
        handler=lambda issue_number, body: _post_comment(installation_id, repo_full_name, issue_number, body, repo_id),
    )


def make_edit_comment(installation_id: int, repo_full_name: str) -> Tool:
    return Tool(
        name="edit_comment",
        description="Edit an existing comment.",
        parameters={
            "type": "object",
            "properties": {
                "comment_id": {"type": "integer", "description": "The comment ID to edit"},
                "body": {"type": "string", "description": "New comment body (markdown)"},
            },
            "required": ["comment_id", "body"],
        },
        handler=lambda comment_id, body: _edit_comment(installation_id, repo_full_name, comment_id, body),
    )
