"""Decision bridge — turn a PRReviewResult into a comment Decision.

Posts the review as a single comment on the PR. Week 5 can upgrade to
inline PR review comments (GitHub's Review API) once we build the
diff-line-to-file-line mapping.
"""
from __future__ import annotations

from gita.agents.decisions import Decision
from gita.agents.types import Finding, PRReviewResult

# Collapse findings into <details> when there are this many or more.
_COLLAPSE_THRESHOLD = 4


def _render_review_body(result: PRReviewResult) -> str:
    """Render the review as a markdown comment body."""
    lines: list[str] = [
        f"## GITA review for PR #{result.pr_number}: `{result.pr_title}`",
        "",
        result.summary,
        "",
    ]

    verdict_emoji = {
        "approve": "APPROVED",
        "comment": "COMMENT",
        "request_changes": "CHANGES REQUESTED",
    }
    lines.append(
        f"**Verdict:** {verdict_emoji.get(result.verdict, result.verdict)}"
    )
    lines.append("")

    if result.findings:
        # Group findings by file for readability.
        by_file: dict[str, list[Finding]] = {}
        for finding in result.findings:
            by_file.setdefault(finding.file, []).append(finding)

        collapse = len(result.findings) >= _COLLAPSE_THRESHOLD
        findings_block: list[str] = []

        for file_path, file_findings in by_file.items():
            findings_block.append(f"### `{file_path}`")
            findings_block.append("")
            for finding in file_findings:
                findings_block.append(
                    f"- **[{finding.severity.upper()}] {finding.kind}** "
                    f"— line {finding.line}: {finding.description}"
                )
                if finding.fix_sketch:
                    findings_block.append(
                        f"  _Fix:_ {finding.fix_sketch}"
                    )
            findings_block.append("")

        if collapse:
            lines.append("<details>")
            lines.append(
                f"<summary>Findings ({len(result.findings)}) "
                f"— click to expand</summary>"
            )
            lines.append("")
            lines.extend(findings_block)
            lines.append("</details>")
            lines.append("")
        else:
            lines.extend(findings_block)
    else:
        lines.append("_No issues found in the changed code._")
        lines.append("")

    lines.append("---")
    lines.append(
        f"_Generated by GITA v0.1.0 PR reviewer. "
        f"Confidence: {result.confidence:.2f}._"
    )
    return "\n".join(lines)


def build_pr_review_decision(
    result: PRReviewResult,
    repo_full_name: str,
    pr_number: int,
) -> Decision:
    """Wrap a PRReviewResult as a ``comment`` Decision on the PR.

    Uses the existing ``comment`` action dispatch — the PR number goes
    into ``target.issue`` because GitHub treats PR comments and issue
    comments as the same endpoint (``POST /issues/{n}/comments``).
    """
    evidence = [
        f"pr_reviewer verdict: {result.verdict}",
        f"{len(result.findings)} findings produced",
        f"confidence: {result.confidence:.2f}",
    ]
    for finding in result.findings[:3]:
        evidence.append(
            f"{finding.severity} {finding.kind} at "
            f"{finding.file}:{finding.line}"
        )

    return Decision(
        action="comment",
        target={"repo": repo_full_name, "issue": pr_number},
        payload={"body": _render_review_body(result)},
        evidence=evidence,
        confidence=result.confidence,
    )
